[general]
static=yes
writeprotect=no

[test]
exten => _X.,1,Answer()
exten => _X.,n,Progress()
exten => _X.,n,Playback(/var/lib/asterisk/sounds/test_beep)
exten => _X.,n,WaitExten(10)
exten => _X.,n,Hangup()
exten => 1,1,Wait(60)
exten => 1,2,Hangup()

[transfer-to-agent]
exten => _X.,1,Dial(PJSIP/${EXTEN}@bitcall-endpoint,60)
exten => _X.,n,Hangup()